// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of attached content.
 */
export type Attachment = { "kind": "image", mime_type: string, 
/**
 * Base64-encoded raw bytes.
 */
data: string, 
/**
 * Optional human-readable description used as a text fallback when
 * the active provider/model does not support vision input.
 */
alt_text: string | null, } | { "kind": "text", filename: string, content: string, };
