// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";

/**
 * Input payload for the `send_message` Tauri command.
 */
export type ChatInput = { 
/**
 * User message text.
 */
message: string, 
/**
 * Optional conversation session identifier.
 */
session_id: string | null, 
/**
 * Optional multi-modal attachments (images, text files).  Vision-capable
 * models receive them as native content blocks; others get text fallbacks.
 */
attachments: Array<Attachment>, };
