// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output payload for the `send_message` Tauri command.
 */
export type ChatOutput = { 
/**
 * Assistant response text.
 */
response: string, 
/**
 * Session identifier (created if not provided in input).
 */
session_id: string, };
