// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted pet state.  All numeric fields are clamped 0..=100 by the
 * host before save; consumers can treat them as percentages.
 */
export type Pet = { 
/**
 * User-visible name.  Defaults to "Hoot" but renameable.
 */
name: string, 
/**
 * Pet level (1+).
 */
level: number, 
/**
 * Experience toward next level. 100 XP / level.
 */
xp: number, 
/**
 * 0 = starving, 100 = fed.
 */
hunger: number, 
/**
 * 0 = depressed, 100 = ecstatic.
 */
happiness: number, 
/**
 * 0 = asleep, 100 = wired.
 */
energy: number, 
/**
 * Wall-clock millis (UTC) of the last `feed` action.
 */
last_fed_ms: bigint, 
/**
 * Wall-clock millis (UTC) of the last user interaction OR agent event
 * — used for idle decay computation.
 */
last_active_ms: bigint, 
/**
 * Cumulative count of successful tool calls the pet has witnessed.
 */
tools_witnessed: bigint, 
/**
 * Optional short cosmetic line — last reaction the pet "said".
 * Ephemeral; persists so reload doesn't strip the last bubble.
 */
last_say: string | null, };
