// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discrete pet-state mutations.  Mapped 1:1 from agent events + user
 * actions in the host layer.
 */
export type PetEvent = { "type": "fed", amount: number, } | { "type": "played" } | { "type": "petted" } | { "type": "tool_success" } | { "type": "tool_failure" } | { "type": "approval_granted" } | { "type": "approval_rejected" } | { "type": "idle", minutes: bigint, };
