// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evolutionary form — owl grows with level.
 */
export type PetForm = "egg" | "chick" | "owlet" | "adult" | "sage";
