// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mood enum derived from the (happiness, hunger, energy) triple.
 *
 * Pure computed property — never persisted; UI re-derives every render.
 */
export type PetMood = "happy" | "content" | "hungry" | "tired" | "sad" | "sleeping" | "excited";
